"""
tools/policy_rag.py — In-process FAISS policy search for the voice agent.
──────────────────────────────────────────────────────────────────────────────
Architecture change from v1 (HTTP RAG) → v2 (In-process FAISS):

  BEFORE:
    agent → HTTP POST localhost:8005/api/search
          → asyncio.to_thread(rag_search)
          → SentenceTransformer.encode()  (300–600ms on CPU)
          → Supabase pgvector RPC          (100–200ms)
          → back to agent                 TOTAL: 600–1200ms

  AFTER:
    agent → in-process FAISS search
          → SentenceTransformer.encode()  (100–300ms, same process, no overhead)
          → faiss.IndexFlatIP.search()    (<1ms in-memory)
          TOTAL: 100–300ms

Prewarm:
  prewarm_policy_index() is called ONCE at worker startup from agent.prewarm().
  It loads the SentenceTransformer model and builds a FAISS IndexFlatIP from
  policy_index/embeddings.npy (generated by scripts/build_policy_index.py).

  All calls within the worker process share these in-memory objects — zero
  per-call model load cost.

Fallback:
  If the index files are missing (e.g. first deploy before build script runs),
  the tool transparently falls back to the original HTTP RAG service.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from pathlib import Path
from typing import Optional

import httpx
from dotenv import load_dotenv
from livekit.agents import function_tool, RunContext

load_dotenv(".env")
logger = logging.getLogger("star-health-agent.policy_rag")

# ── HTTP fallback URL (used only if in-process index is unavailable) ──────────
RAG_API_URL = os.getenv("RAG_API_URL", "http://localhost:8005")

# ── In-process index globals (populated by prewarm_policy_index) ──────────────
_policy_model = None          # SentenceTransformer
_policy_faiss_index = None    # faiss.IndexFlatIP
_policy_chunks_meta: Optional[list[dict]] = None   # [{text, policy}, ...]

_POLICY_INDEX_DIR = Path(__file__).parent.parent / "policy_index"
_MIN_SIMILARITY = 0.20        # same threshold as rag.py


# ── Prewarm ────────────────────────────────────────────────────────────────────

def prewarm_policy_index() -> None:
    """
    Load the SentenceTransformer model and FAISS index into module-level
    globals.  Called ONCE from agent.prewarm() at worker startup — never
    per-call.  All concurrent calls within the same worker share these objects.

    Requires:
        policy_index/chunks.json       — generated by scripts/build_policy_index.py
        policy_index/embeddings.npy    — generated by scripts/build_policy_index.py
    """
    global _policy_model, _policy_faiss_index, _policy_chunks_meta

    chunks_path = _POLICY_INDEX_DIR / "chunks.json"
    embeddings_path = _POLICY_INDEX_DIR / "embeddings.npy"

    if not chunks_path.exists() or not embeddings_path.exists():
        logger.warning(
            "Policy index not found at '%s'. "
            "Run: python scripts/build_policy_index.py   "
            "→ RAG tool will fall back to HTTP until index is built.",
            _POLICY_INDEX_DIR,
        )
        return

    try:
        import faiss  # type: ignore
        import numpy as np
        from sentence_transformers import SentenceTransformer  # type: ignore

        logger.info("Prewarming policy search: loading SentenceTransformer (all-MiniLM-L6-v2)...")
        _policy_model = SentenceTransformer("all-MiniLM-L6-v2", device="cpu")

        logger.info("Prewarming policy search: building FAISS index from %s ...", embeddings_path)
        with open(chunks_path, "r", encoding="utf-8") as f:
            _policy_chunks_meta = json.load(f)

        embeddings = np.load(str(embeddings_path)).astype(np.float32)
        dim = embeddings.shape[1]

        # IndexFlatIP performs exact inner-product search.
        # Embeddings are already L2-normalised in build_policy_index.py,
        # so inner product == cosine similarity.
        index = faiss.IndexFlatIP(dim)
        index.add(embeddings)
        _policy_faiss_index = index

        logger.info(
            "Policy FAISS index ready: %d chunks, dim=%d (%.1f MB in RAM)",
            len(_policy_chunks_meta),
            dim,
            (embeddings.nbytes / 1024 / 1024),
        )

    except ImportError as e:
        logger.error(
            "Missing dependency for in-process search (%s). "
            "Install with: pip install faiss-cpu sentence-transformers numpy. "
            "→ RAG tool will fall back to HTTP.",
            e,
        )
    except Exception as e:
        logger.error(
            "Failed to prewarm policy index: %s → RAG tool will fall back to HTTP.", e
        )
        _policy_model = None
        _policy_faiss_index = None
        _policy_chunks_meta = None


# ── Search helpers ─────────────────────────────────────────────────────────────

async def _search_in_process(query: str, top_k: int = 3) -> list[dict]:
    """
    Encode the query and search the in-memory FAISS index.
    Runs in a thread-pool executor so it never blocks the asyncio event loop.
    """
    import numpy as np

    def _sync() -> list[dict]:
        # encode() is CPU-bound; run in executor thread
        query_emb = _policy_model.encode(
            [query],
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=False,
        ).astype("float32")

        scores, indices = _policy_faiss_index.search(query_emb, top_k)
        results = []
        for score, idx in zip(scores[0], indices[0]):
            if idx >= 0 and float(score) >= _MIN_SIMILARITY:
                chunk = _policy_chunks_meta[idx]
                results.append(
                    {
                        "content": chunk.get("text", ""),
                        "policy": chunk.get("policy", ""),
                        "score": float(score),
                    }
                )
        return results

    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync)


async def _search_http_fallback(query: str) -> list[dict]:
    """
    HTTP fallback — calls the star-health-rag /api/search endpoint.
    Used only when the in-process FAISS index has not been built yet.
    """
    logger.warning("Using HTTP RAG fallback for policy search (index not loaded)")
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.post(
                f"{RAG_API_URL}/api/search",
                json={"query": query, "limit": 3},
            )
            response.raise_for_status()
            data = response.json()
        return data.get("results", [])
    except httpx.TimeoutException:
        logger.warning("HTTP RAG fallback timed out for query: %s", query)
        return []
    except Exception as e:
        logger.error("HTTP RAG fallback failed: %s", e)
        return []


# ── Tool ───────────────────────────────────────────────────────────────────────

@function_tool()
async def search_policies(context: RunContext, query: str) -> str:
    """
    Search Star Health policy documents for a specific customer question.
    Call this tool for detailed questions about: waiting periods, sub-limits,
    exclusions, room rent caps, claim process, specific benefit details, co-pay rules,
    or any policy specifics not covered by your general knowledge.
    Do NOT call this for general plan comparisons — use your built-in knowledge for those.

    Args:
        query: The customer's question or the specific detail you need to look up.
    """
    logger.info("Policy search (in-process=%s): %s", _policy_faiss_index is not None, query)

    if _policy_model is not None and _policy_faiss_index is not None:
        chunks = await _search_in_process(query)
    else:
        chunks = await _search_http_fallback(query)

    if not chunks:
        logger.warning("No policy chunks found for query: %s", query)
        return "I don't have specific details on that, but I can connect you with our product team."

    combined = " ".join(c.get("content", "") for c in chunks[:3])
    return combined[:500] if len(combined) > 500 else combined
