"""
tools/policy_rag.py — In-process FAISS policy search for the voice agent.
──────────────────────────────────────────────────────────────────────────────
Architecture change from v1 (HTTP RAG) → v2 (In-process FAISS):

  BEFORE:
    agent → HTTP POST localhost:8005/api/search
          → asyncio.to_thread(rag_search)
          → SentenceTransformer.encode()  (300–600ms on CPU)
          → Supabase pgvector RPC          (100–200ms)
          → back to agent                 TOTAL: 600–1200ms

  AFTER:
    agent → in-process FAISS search
          → SentenceTransformer.encode()  (100–300ms, same process, no overhead)
          → faiss.IndexFlatIP.search()    (<1ms in-memory)
          TOTAL: 100–300ms

Prewarm:
  prewarm_policy_index() is called ONCE at worker startup from agent.prewarm().
  It loads the SentenceTransformer model and builds a FAISS IndexFlatIP from
  policy_index/embeddings.npy (generated by scripts/build_policy_index.py).

  All calls within the worker process share these in-memory objects — zero
  per-call model load cost.

Fallback:
  If the index files are missing (e.g. first deploy before build script runs),
  the tool transparently falls back to the original HTTP RAG service.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from pathlib import Path
from typing import Optional

import httpx
from dotenv import load_dotenv
from livekit.agents import function_tool, RunContext

load_dotenv(".env")
logger = logging.getLogger("star-health-agent.policy_rag")

# ── HTTP fallback URL (used only if in-process index is unavailable) ──────────
RAG_API_URL = os.getenv("RAG_API_URL", "http://localhost:8005")

# ── In-process index globals (populated by prewarm_policy_index) ──────────────
_policy_model = None          # SentenceTransformer
_policy_faiss_index = None    # faiss.IndexFlatIP
_policy_chunks_meta: Optional[list[dict]] = None   # [{text, policy}, ...]

_POLICY_INDEX_DIR = Path(__file__).parent.parent / "policy_index"
_MIN_SIMILARITY = 0.20        # same threshold as rag.py


# ── Prewarm ────────────────────────────────────────────────────────────────────

def prewarm_policy_index() -> None:
    """
    Load the SentenceTransformer model and FAISS index into module-level
    globals.  Called ONCE from agent.prewarm() at worker startup — never
    per-call.  All concurrent calls within the same worker share these objects.

    Requires:
        policy_index/chunks.json       — generated by scripts/build_policy_index.py
        policy_index/embeddings.npy    — generated by scripts/build_policy_index.py
    """
    global _policy_model, _policy_faiss_index, _policy_chunks_meta

    chunks_path = _POLICY_INDEX_DIR / "chunks.json"
    embeddings_path = _POLICY_INDEX_DIR / "embeddings.npy"

    if not chunks_path.exists() or not embeddings_path.exists():
        logger.warning(
            "Policy index not found at '%s'. "
            "Run: python scripts/build_policy_index.py   "
            "→ RAG tool will fall back to HTTP until index is built.",
            _POLICY_INDEX_DIR,
        )
        return

    try:
        import faiss  # type: ignore
        import numpy as np
        from sentence_transformers import SentenceTransformer  # type: ignore

        logger.info("Prewarming policy search: loading SentenceTransformer (all-MiniLM-L6-v2)...")
        _policy_model = SentenceTransformer("all-MiniLM-L6-v2", device="cpu")

        logger.info("Prewarming policy search: building FAISS index from %s ...", embeddings_path)
        with open(chunks_path, "r", encoding="utf-8") as f:
            _policy_chunks_meta = json.load(f)

        embeddings = np.load(str(embeddings_path)).astype(np.float32)
        dim = embeddings.shape[1]

        # IndexFlatIP performs exact inner-product search.
        # Embeddings are already L2-normalised in build_policy_index.py,
        # so inner product == cosine similarity.
        index = faiss.IndexFlatIP(dim)
        index.add(embeddings)
        _policy_faiss_index = index

        logger.info(
            "Policy FAISS index ready: %d chunks, dim=%d (%.1f MB in RAM)",
            len(_policy_chunks_meta),
            dim,
            (embeddings.nbytes / 1024 / 1024),
        )

    except ImportError as e:
        logger.error(
            "Missing dependency for in-process search (%s). "
            "Install with: pip install faiss-cpu sentence-transformers numpy. "
            "→ RAG tool will fall back to HTTP.",
            e,
        )
    except Exception as e:
        logger.error(
            "Failed to prewarm policy index: %s → RAG tool will fall back to HTTP.", e
        )
        _policy_model = None
        _policy_faiss_index = None
        _policy_chunks_meta = None


# ── Search helpers ─────────────────────────────────────────────────────────────

async def _search_in_process(query: str, top_k: int = 3) -> list[dict]:
    """
    Encode the query and search the in-memory FAISS index.
    Runs in a thread-pool executor so it never blocks the asyncio event loop.
    """
    import numpy as np

    def _sync() -> list[dict]:
        # encode() is CPU-bound; run in executor thread
        query_emb = _policy_model.encode(
            [query],
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=False,
        ).astype("float32")

        scores, indices = _policy_faiss_index.search(query_emb, top_k)
        results = []
        for score, idx in zip(scores[0], indices[0]):
            if idx >= 0 and float(score) >= _MIN_SIMILARITY:
                chunk = _policy_chunks_meta[idx]
                results.append(
                    {
                        "content": chunk.get("text", ""),
                        "policy": chunk.get("policy", ""),
                        "score": float(score),
                    }
                )
        return results

    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync)


async def _search_http_fallback(query: str) -> list[dict]:
    """
    HTTP fallback — calls the star-health-rag /api/search endpoint.
    Used only when the in-process FAISS index has not been built yet.
    """
    logger.warning("Using HTTP RAG fallback for policy search (index not loaded)")
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.post(
                f"{RAG_API_URL}/api/search",
                json={"query": query, "limit": 3},
            )
            response.raise_for_status()
            data = response.json()
        return data.get("results", [])
    except httpx.TimeoutException:
        logger.warning("HTTP RAG fallback timed out for query: %s", query)
        return []
    except Exception as e:
        logger.error("HTTP RAG fallback failed: %s", e)
        return []


# ── Speech-safe output cleaner ─────────────────────────────────────────────────

import re

def _clean_for_speech(text: str) -> str:
    """
    Strip policy codes, UINs, IRDAI reference numbers, CIN codes and other
    non-speakable tokens from RAG chunk text before returning to the LLM.

    Patterns removed:
      - UIN codes        e.g. SHAHLIP21042V032021, UIN: XYZ123
      - CIN numbers      e.g. L66010TN1973PLC005793
      - IRDAI reg codes  e.g. IRDAI/HLT/SHI/P-H/V.I/164/2013-14
      - Section/item codes like 009400, A-009, Sec-IV-B
      - Bare long numbers >6 digits that aren't prices (prices have ₹/Rs/Lakh/Crore context)
      - Slash-delimited reference strings  e.g. IRDA/NL-HLT/SHAI/P-H/V.I/321/12-13
    """
    # Remove UIN lines/inline (key: value style)
    text = re.sub(r'\bU\.?I\.?N\.?\s*[:\-]?\s*[A-Z0-9]{8,30}\b', '', text, flags=re.IGNORECASE)

    # Remove CIN numbers (company identification numbers)
    text = re.sub(r'\b[A-Z]\d{5}[A-Z]{2}\d{4}[A-Z]{3}\d{6}\b', '', text)

    # Remove IRDAI/IRDA slash-reference codes
    text = re.sub(r'\bIRDA[I]?/[\w\-/]+', '', text, flags=re.IGNORECASE)

    # Remove standalone alphanumeric codes: 3+ letters followed by 4+ digits (or vice versa)
    # e.g. SHI2021, SHAI164, P-H, V.I but NOT plan names like "Young Star"
    text = re.sub(r'\b[A-Z]{2,6}[\-/]?[A-Z0-9]{3,}[\-/]?[A-Z0-9]*\b(?!\s*(plan|star|health|assure|optima|classic|premier|comprehensive|sanjeevani))', '', text)

    # Remove standalone long digit strings >6 digits that are not rupee amounts
    # Keep: "5 Lakh", "10,000", "₹699" — remove: "009400", "12345678"
    text = re.sub(r'(?<![₹,\d])\b0*\d{6,}\b(?!\s*(lakh|crore|rupee|per|month|year|day|%|,))', '', text, flags=re.IGNORECASE)

    # Remove section codes like "Sec-IV-B", "Cl. 3.2.1", "Item 009"
    text = re.sub(r'\b(sec|cl|item|clause|para|pt|sch|ann)[\.\-\s]?[IVX\d\.]+\b', '', text, flags=re.IGNORECASE)

    # Remove file/form numbers like "F-125/2021", "Form HLT-01"
    text = re.sub(r'\b(form|file|ref|no\.?)\s*[\w\-/]{3,}\b', '', text, flags=re.IGNORECASE)

    # Clean up extra whitespace left by removals
    text = re.sub(r'\s{2,}', ' ', text).strip()
    text = re.sub(r'\s+([,\.\;\:])', r'\1', text)

    return text


# ── Tool ───────────────────────────────────────────────────────────────────────

@function_tool()
async def search_policies(context: RunContext, query: str) -> str:
    """
    Search Star Health policy documents for a specific customer question.
    Call this tool for detailed questions about: waiting periods, sub-limits,
    exclusions, room rent caps, claim process, specific benefit details, co-pay rules,
    or any policy specifics not covered by your general knowledge.
    Do NOT call this for general plan comparisons — use your built-in knowledge for those.

    Args:
        query: The customer's question or the specific detail you need to look up.
    """
    import config
    lead = context.userdata.get("lead") or {}
    rec_plan = lead.get("recommended_plan_id") or lead.get("recommended_plan") or ""
    rec_plan_name = config.PLAN_NAME_MAP.get(rec_plan, rec_plan)

    search_query = query
    if rec_plan_name and rec_plan_name.lower() not in query.lower():
        search_query = f"{rec_plan_name} {query}"

    logger.info("Policy search (query='%s', augmented='%s', in-process=%s)", query, search_query, _policy_faiss_index is not None)

    if _policy_model is not None and _policy_faiss_index is not None:
        chunks = await _search_in_process(search_query)
    else:
        chunks = await _search_http_fallback(search_query)


    if not chunks:
        logger.warning("No policy chunks found for query: %s", query)
        return "I don't have specific details on that, but I can connect you with our product team."

    combined = " ".join(c.get("content", "") for c in chunks[:3])
    combined = combined[:600] if len(combined) > 600 else combined

    # Strip policy codes / UINs / reference numbers before sending to LLM
    cleaned = _clean_for_speech(combined)

    if not cleaned.strip():
        return "I don't have specific details on that. Our product team can share the complete policy document."

    logger.info("RAG cleaned output (%d→%d chars): %s", len(combined), len(cleaned), cleaned[:120])
    return cleaned
